FROM node:22-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install

EXPOSE 3000
ENV PORT=3000

CMD ["pnpm", "dev"]
